### ISSUE TITLE
Consider adding system font stack behind custom family

### ISSUE THREAD

**Issue by rootEnginear** [wevisdemo/design-systems#7]
https://github.com/wevisdemo/design-systems/blob/e6992630b864167eb9fb651d421b682641387673/ui/src/styles/typography.css#L48-L59

From the code above, there are 1 problem and 1 potential improvement

1. The `"serif"` and `"sans"` value are incorrect: It should be `serif` (without quotes) and `sans-serif` (also without quotes).
2. Add system font stack behind the main family.

## System Font Stack

Normally, when a browser cannot find the font/waiting for a font to download/cannot find particular glyphs, it will tried to find in the following fonts. You can use this opportunity to stack default fonts on each OS into the stack so it can be used quickly.

In Tailwind, the default stack are:

| Class | Properties |
| --- | --- |
| `font-sans` | font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; |
| `font-serif` | font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif; |
| `font-mono` | font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; |

We can use this to fallback our main family.

> See [Font Family - Tailwind CSS](https://tailwindcss.com/docs/font-family#class-reference)

## Purposed Fix

```css
/* Font family */ 
.wv-font-kondolar { 
  font-family: "Kondolar Thai", ui-serif, Georgia, Cambria, "Times New Roman", Times, serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
} 

.wv-font-anuphan { 
  font-family: Anuphan, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
} 

.wv-font-baijamjuri { 
  font-family: "Bai Jamjuri", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
} 
```
